# Generated by Django 4.1.7 on 2023-02-26 03:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Representative",
            fields=[
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=10, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("d65f537c-fb89-4afe-bbb0-d6737bfc50e7"),
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("phone", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("delivery_address", models.TextField()),
                ("products_data", models.TextField()),
                (
                    "pk_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Orders.representative",
                    ),
                ),
            ],
        ),
    ]
