# Generated by Django 4.1.7 on 2023-02-26 03:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("Orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="rep_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Orders.representative",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="delivery_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="products_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="representative",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("acd35561-0d08-4bc5-a48f-d428d84ae2d5"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
