# Generated by Django 4.1.7 on 2023-02-26 05:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("Orders", "0002_customer_rep_name_alter_customer_delivery_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representative",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e2112c7c-fbf4-4cf7-87d4-5f4b757c5e5d"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
